services:
  web:
    build: ./
    volumes:
      - library_files:/usr/src/app/
    ports:
      - 5001:5000
    env_file:
      - ./.env.docker
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    image: percona:ps-8.0
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_USER=easylib
      - MYSQL_PASSWORD=easylib
      - MYSQL_ROOT_PASSWORD=easylib
      - MYSQL_DATABASE=easylib
    ports:
      - 3310:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-peasylib","ping"]
      start_period: 12s
      interval: 10s
      timeout: 5s
      retries: 12

volumes:
  db_data:
  library_files: