"""empty message

Revision ID: 43d67e580900
Revises: c21735afbf9f
Create Date: 2024-07-19 20:37:39.667137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '43d67e580900'
down_revision = 'c21735afbf9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=500),
               type_=sa.String(length=500).with_variant(mysql.NVARCHAR(national=True, length=500), 'mariadb').with_variant(mysql.NVARCHAR(national=True, length=500), 'mysql'),
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=15000),
               type_=sa.String(length=15000).with_variant(mysql.NVARCHAR(national=True, length=15000), 'mariadb').with_variant(mysql.NVARCHAR(national=True, length=15000), 'mysql'),
               existing_nullable=True)

    with op.batch_alter_table('bookborrow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hasResolved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookborrow', schema=None) as batch_op:
        batch_op.drop_column('hasResolved')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.String(length=15000).with_variant(mysql.NVARCHAR(national=True, length=15000), 'mariadb').with_variant(mysql.NVARCHAR(national=True, length=15000), 'mysql'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=15000),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=500).with_variant(mysql.NVARCHAR(national=True, length=500), 'mariadb').with_variant(mysql.NVARCHAR(national=True, length=500), 'mysql'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
